version: '2'
services:
  # app:
  #   build: .
  #   environment:
  #     - PORT=3000
  #     - MONGO_URL=mongodb:27017
  #   ports:
  #     - "3000:3000"
  #   links:
  #     - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
